version: '3'

services:
  app:
    image: shawanatobi/groupprojectimage:1.0
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MONGO_URI: "mongodb+srv://giddyshawy:rLpIzhqGa558IuLw@devops.8woj8ue.mongodb.net/server?retryWrites=true&w=majority"
  db:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example