version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8086"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://giddyshawy:rLpIzhqGa558IuLw@devops.8woj8ue.mongodb.net/server?retryWrites=true&w=majority
    depends_on:
      - db

  db:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

