pipeline {
    agent any

    tools {
        git 'G3'
        maven 'M3'
    }

    environment {
        DOCKERHUB_PWD = credentials('docker-jenkins')
    }

    triggers {
        pollSCM('*/5 * * * *') // Poll SCM every 5 minutes
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/shawanaGideon/comp367-group-project.git'
            }
        }

        stage('Build Maven Project') {
            steps {
                dir('server') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('server') {
                    sh 'docker build -t shawanatobi/groupprojectimage:1.0 .'
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-jenkins', usernameVariable: 'shawana', passwordVariable: 'DOCKERHUB_PWD')]) {
                    sh 'echo "$DOCKERHUB_PWD" | docker login -u shawana --password-stdin'
                }
            }
        }

        stage('Deploy to Dev Env') {
            steps {
                dir('server') {
                    sh 'docker-compose -f docker-compose-dev.yml up -d'
                }
            }
        }

        stage('Deploy to QAT Env') {
            steps {
                dir('server') {
                    sh 'docker-compose -f docker-compose-qat.yml up -d'
                }
            }
        }

        stage('Deploy to Staging Env') {
            steps {
                dir('server') {
                    sh 'docker-compose -f docker-compose-staging.yml up -d'
                }
            }
        }

        stage('Deploy to Production Env') {
            steps {
                dir('server') {
                    sh 'docker-compose -f docker-compose-prod.yml up -d'
                }
            }
        }
    }
}
