pipeline {
    agent any

    tools {
        git 'G3'
        maven 'M3'
    }

    environment {
        DOCKERHUB_PWD = credentials('docker-jenkins')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/shawanaGideon/comp367-group-project.git'
            }
        }

        stage('Build Maven Project') {
            steps {
                dir('server') {
                    // Navigate to the directory containing pom.xml
                    sh 'mvn clean package'
                }
            }
        }

        stage('Code Coverage') {
            steps {
                dir('server') {
                    // Navigate to the directory containing pom.xml
                    sh 'mvn clean test jacoco:prepare-agent jacoco:report'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('server') {
                    // Navigate to the directory containing Dockerfile
                    sh 'docker build -t shawanatobi/groupprojectimage:1.0 .'
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-jenkins', usernameVariable: 'shawana', passwordVariable: 'DOCKERHUB_PWD')]) {
                    sh '''
                        echo "$DOCKERHUB_PWD" | docker login -u shawana --password-stdin
                    '''
                }
            }
        }

        stage('Deploy to Dev Env') {
            steps {
                dir('server') {
                    // Deploy artifact to development environment
                    sh 'docker-compose -f docker-compose-dev.yml up -d'
                }
            }
        }

        stage('Deploy to QAT Env') {
            steps {
                dir('server') {
                    // Deploy artifact to QA/testing environment
                    sh 'docker-compose -f docker-compose-qat.yml up -d'
                }
            }
        }

        stage('Deploy to Staging Env') {
            steps {
                dir('server') {
                    // Deploy artifact to staging environment
                    sh 'docker-compose -f docker-compose-staging.yml up -d'
                }
            }
        }

        stage('Deploy to Production Env') {
            steps {
                dir('server') {
                    // Deploy artifact to production environment
                    sh 'docker-compose -f docker-compose-prod.yml up -d'
                }
            }
        }
    }
}
