pipeline {
    agent any

    tools {
        git 'G3'
        maven 'M3'
    }

    environment {
        DOCKERHUB_PWD = credentials('docker-jenkins')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/shawanaGideon/comp367-group-project.git'
            }
        }

        stage('Build Maven Project') {
            steps {
                dir('server') { // Navigate to the directory containing pom.xml
                    sh 'mvn clean package'
                }
            }
        }

        stage('Code Coverage') {
            steps {
                dir('server') { // Navigate to the directory containing pom.xml
                    sh 'mvn clean test jacoco:prepare-agent jacoco:report'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('server') { // Navigate to the directory containing Dockerfile
                    sh 'docker build -t shawanatobi/groupprojectimage:1.0 .'
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-jenkins', usernameVariable: 'shawana', passwordVariable: 'DOCKERHUB_PWD')]) {
                    sh '''
                        echo "$DOCKERHUB_PWD" | docker login -u shawana --password-stdin
                    '''
                }
            }
        }

        stage('Docker Push') {
            steps {
                sh 'docker push shawanatobi/groupprojectimage:1.0'
            }
        }
    }
}
